jobs:
  - name: dv-man
    type: manifest
    steps:
      - IN: dv-image
        pull: false
      - IN: dv-opts
      - IN: dv-params
        applyTo:
          - dv-image
      - TASK: managed
      - IN: trigger-dv-man
    on_success:
      - script: echo 'this is on_success step of dv-man of type manifest'
    on_failure:
      - script: echo 'this is on_failure step of dv-man of type manifest'

  - name: dv-man-versionName
    type: manifest
    steps:
      - IN: dv-image
        pull: false
        versionName: latest
      - IN: dv-opts
      - IN: dv-params
        applyTo:
          - dv-image
      - TASK: managed
      - IN: trigger-dv-man

- name: dv-man-versionName-1
    type: manifest
    steps:
      - IN: dv-image      

- name: dv-man-versionName-2
    type: manifest
    steps:
      - IN: dv-image      
 
  - name: dv-man-versionNumber
    type: manifest
    steps:
      - IN: dv-image
        pull: false
        versionNumber: 1
      - IN: dv-opts
      - IN: dv-params
        applyTo:
          - dv-image
      - TASK: managed
      - IN: trigger-dv-man

  - name: dv-test
    type: deploy
    on_start:
      - NOTIFY: slackNotification
    steps:
      - IN: dv-man
      - IN: env-test
      - TASK: managed
        deployMethod: upgrade
    on_success:
      - NOTIFY: slackNotifcation
    on_failure:
      - NOTIFY: slackNotification

  - name: box-man
    type: manifest
    steps:
      - IN: box-image
        pull: false
      - IN: box-opts
      - IN: box-params
      - TASK: managed

  - name: box-test
    type: deploy
    steps:
      - IN: box-man
      - IN: env-test
      - TASK: managed
        deployMethod: upgrade

  - name: box-dcl
    type: deploy
    steps:
      - IN: box-man
      - IN: env-dcl
      - TASK: managed

  - name: box-gke
    type: deploy
    steps:
      - IN: box-man
      - IN: env-gke
      - TASK: managed

  - name: box-prod
    type: deploy
    steps:
      - IN: box-man
        switch: off
      - IN: env-prod
      - TASK: managed

  - name: multi-manifest
    type:  deploy
    steps:
      - IN: box-man
      - IN: dv-man
      - IN: env-test
      - TASK: managed
        deployMethod: upgrade

  - name: release-one
    type: release
    steps:
      - IN: version-resource
      - IN: dv-man
      - TASK: managed
        bump: major

  - name: box-tripub-man
    type: manifest
    steps:
      - IN: box-image
        pull: false
      - IN: box-tripub-opts
      - TASK: managed

  - name: box-tripub
    type: deploy
    steps:
      - IN: box-tripub-man
      - IN: env-tripub
      - TASK: managed

  - name: infra-provision
    type: runSh
    steps:
      - IN: infra-repo
      - TASK:
        - script: ls
        - script: ./GET/infra-repo/infra-repo/provision.sh
    on_success:
      - script: echo 'This block executes after TASK section executes successfully'
      - NOTIFY: slackNotifcation

  - name: build-dv-image
    type: runSh
    steps:
      - IN: infra-repo
      - TASK:
        - script: "echo 'versionName=latest' > /build/state/dv-image.env"
      - OUT: dv-image
